### ISSUE TITLE
Ustalenie technologii szkieletu

### ISSUE THREAD

**Issue by gtwsky** [conehow/Blue-Steenbok#1]
Trzeba ustalić w jakim jezyku bedziemy pisac i jakie technologie bedziemy wkorzystywac jako szkielet portalu.

Moje propozycje to:
Python (Django)
NodeJS,
Go (Revel, Martini)

**Comment by emsi93** [comment]
Część back-endu:

kotlin + spring boot + spring data + JPA + maven 

@gtwsky hir
Do postawienie bedzie podstawowe echo. Server bedzie zwracal cokolwiek sie na niego wysle.

Na poczatek baza danych w backendzie bedzie kozystala z H2. Wydzielic odpowienio mechanizm, ktory pozwoli na łatwa zmiane bazy danych.

Ja stworze repozytorium do backendu i napisze dokladniejsze wymagania.

**Comment by gtwsky** [comment]
@emsi93 
Moze nie powinienem już stawiać osobnego repo pod front, tylko wykorzystamy to repo jako front.
Pytanie:
Jaka technologia do frontu ? Gadalismy wczesniej o NodeJS, to jest cos co ogarniam (Reszta to bedzie pierwszy raz).
Wszystkie te co wymienilem mi pasuja bo czegos sie z nich naucze. Co ty sądzisz?

**Comment by gtwsky** [comment]
Jeśli miałbym się zdecydować na używanie Node jako core portalu, to jako framework powinniśmy zastosować albo ReactJS albo Vue. Z Angulara chyba powinniśmy zrezygnować, ponieważ jest to duża kobyła i jest mocno zopiniowany (będziemy zmuszeni robić wszystko "the Angular Way").

**Comment by gtwsky** [comment]
@emsi93 
Spójrz na Vue 2 (https://vuejs.org/v2/guide/index.html)
oraz React (https://reactjs.org/tutorial/tutorial.html)

Co według ciebie wygląda na bardziej przystępną biblioteke? (Wygląd, architektura itd)
Nie moge się między nimi zdecydować, bo ich założenia są identyczne i mają parcie w na rynku. 

Potrzebuje pomocy w podjęciu decyzji :)

**Comment by gtwsky** [comment]
Szkielet aplikacji portalu to Vue 2.
