### ISSUE TITLE
Wprowadzenie Progressive Web Application

### ISSUE THREAD

**Issue by gtwsky** [conehow/Blue-Steenbok#3]
Pomyślałem, że możnaby wykorzystać ten projekt do wprowadzenia i nauczenia się robienia aplikacji PWA. Pozwoli nam to używać tego projektu jednocześnie jako aplikacji webowej i mobilnej.

Prawdopodobnie będę musiał zmienić szkielet aplikacji na template _pwa_ przy uzyciu vue-cli.

Co o tym sądzicie?

**Comment by emsi93** [comment]
ja myślę, że to jest fajny pomysł, widziałem jak to działa, więc można tez o tym pomyśleć

**Comment by gtwsky** [comment]
To zajme się zmianą szablonu, podłączeniem dockera i będę mógł zacząć pisać widok główny

**Comment by gtwsky** [comment]
Postawiłem szkielet, PWA działa, docker dla developera tez dziala (docker-compose), ale image produkcyjny jeszcze nie działa.

**Comment by gtwsky** [comment]
Sprawdziłem dokładniej co robiłem źle, i obydwie wersje dockera (prod i dev) działają poprawnie, sprawdźcie czy wam pasuje to jak wygląda szkielet, to po zmergowaniu będę mógł zacząć pisać front.

**Comment by gtwsky** [comment]
Code review zrobione przez @emsi93 
Skończone i zmergowane
