### ISSUE TITLE
Propozycja komunikatora

### ISSUE THREAD

**Issue by emsi93** [conehow/Blue-Steenbok#4]
Co myslicie na temat jakiegos komunikatora? Github nie posiada własnego chatu, nawet mobilnego klienta,
dodatkowo co raz wiecej jest nas w teamie i czasem latwiej bedzie zapytac i odpowiedziec na jakims zewnetrznym komunikatorze, niz komentowac taski w gicie.

Proponuje slacka, korzystalismy w pracy przez moment, jest tez apka mobilna.

**Comment by gtwsky** [comment]
Pytanie powinno być w gajdlajnsach a nie w repo od frontu do BS, ale trudno :D.

Pomysł myślę że bardzo dobry, bo jak @emsi93 mowi będzie łatwo można oddzielić samą gadkę konkretną na temat tasków od luźnej rozmowy i pomocy.

Postaram się stworzyć nam Slacka i będziemy się poprzez apkę komunikować. Namiary dam tu.

Na przyszłość proponuje inne rozwiązanie, może napiszmy własną aplikacje mobilną, która będzie nam służyła do komunikacji? Na takim projekcie można pocwiczyć tworzenie aplikacji na androida + spróbować coś z WebRTC.

**Comment by gtwsky** [comment]
Przeniesiono do conehow/guidelines#1
