### ISSUE TITLE
Zaprojektować główny layout apki

### ISSUE THREAD

**Issue by gtwsky** [conehow/Blue-Steenbok#5]
Zrobić głowny layout pod aplikacje

**Comment by gtwsky** [comment]
Zrób review podstawowego layoutu apki.

Narazie to tylko layout więc nie spodziewaj się cudów, bo dopiero one teraz będą implementowane.

Jeśli nie masz zastrzeżeń to napisz tu że zaklepujesz to zrobie merge i zajme się albo widokiem rejestracji albo hamburger menu.

**Comment by emsi93** [comment]
Zrobilem code review, nie mam zastrzezen
